# Generated by Django 5.1.7 on 2025-03-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('type_user', models.CharField(choices=[('ADMIN', 'Admin'), ('OWNER', 'Owner'), ('USER', 'User'), ('GUEST', 'Guest')], default='USER', max_length=5)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
